### ISSUE TITLE
[TODO] A tool list about what harborctl will support

### ISSUE THREAD

**Issue by moooofly** [moooofly/harborctl#12]
- [ ] a password reset tool
- [x] a sync status diagnosing tool
- [ ] a tags analyzing tool
- [ ] a repositories analyzing tool
