### ISSUE TITLE
refactor replication related APIs hierarchy

### ISSUE THREAD

**Issue by moooofly** [moooofly/harborctl#41]
As https://github.com/moooofly/harborctl/issues/5#issuecomment-449804308

> Suggest use `replication` instead of `job`: 
>
> - `harborctl replication policy *`
> - `harborctl replication run *`
> - `harborctl replication log *` etc.

## before

- [x] job
    - [x] replication
        - [x] list (https://github.com/moooofly/harborctl/issues/28)
        - [x] update
        - [x] delete
        - [x] log
    - [x] scan
        - [x] log (https://github.com/moooofly/harborctl/issues/29)
- [ ] policy
    - [ ] replication
        - [x] list
        - [x] get
        - [ ] create (https://github.com/moooofly/harborctl/issues/30, https://github.com/moooofly/harborctl/issues/31, rely on "/targets" API)
        - [ ] update (https://github.com/moooofly/harborctl/issues/33, rely on "/targets" API)
        - [x] delete (https://github.com/moooofly/harborctl/issues/32)
- [x] replication
    - [x] trigger

## after

- [x] replication
    - [x] list (https://github.com/moooofly/harborctl/issues/28)
    - [x] update
    - [x] delete
    - [x] log
- [x] scan
    - [x] log (https://github.com/moooofly/harborctl/issues/29)
- [ ] replication
    - [ ] policy
        - [x] list
        - [x] get
        - [ ] create (https://github.com/moooofly/harborctl/issues/30, https://github.com/moooofly/harborctl/issues/31, rely on "/targets" API)
        - [ ] update (https://github.com/moooofly/harborctl/issues/33, rely on "/targets" API)
        - [x] delete (https://github.com/moooofly/harborctl/issues/32)
- [x] replication
    - [x] trigger

**Comment by moooofly** [comment]
related to https://github.com/moooofly/harborctl/commit/9415e788a09b5066c525a1c540e012bb0fd0bea8
