### ISSUE TITLE
[TODO] A comman list about what harborctl will support

### ISSUE THREAD

**Issue by moooofly** [moooofly/harborctl#5]
a scratch about what `harborctl` will support.

------

command list:

- [x] login
- [x] logout
- [x] search
- [x] project
    - [x] check
    - [x] create
    - [x] delete
    - [x] get
    - [x] list
    - [x] update (https://github.com/moooofly/harborctl/issues/1)
    - [x] member
        - [x] create
        - [x] delete
        - [x] get
        - [x] list
        - [x] update
    - [x] metadata
        - [x] create (https://github.com/moooofly/harborctl/issues/3)
        - [x] delete
        - [x] get
        - [x] list
        - [x] update (https://github.com/moooofly/harborctl/issues/4)
    - [x] log (https://github.com/moooofly/harborctl/issues/2)
- [x] statistics
- [x] user
    - [x] list
    - [x] create (https://github.com/moooofly/harborctl/issues/7, https://github.com/moooofly/harborctl/issues/9)
    - [x] current
    - [x] get
    - [x] update (https://github.com/moooofly/harborctl/issues/10)
    - [x] delete
    - [x] password (https://github.com/moooofly/harborctl/issues/11)
    - [x] sysadmin
- [x] repository
    - [x] top
    - [x] get (https://github.com/moooofly/harborctl/issues/13)
    - [x] delete
    - [x] update
    - [x] label
        - [x] get
        - [x] add (https://github.com/moooofly/harborctl/issues/20, rely on "/labels" API)
        - [x] delete
    - [x] tag
        - [x] get
        - [x] delete
        - [x] list (rely on "/labels" API)
        - [x] retag (https://github.com/moooofly/harborctl/issues/17)
        - [x] label
            - [x] get
            - [x] add (https://github.com/moooofly/harborctl/issues/21, rely on "/labels" API)
            - [x] delete
        - [x] manifest
        - [x] scan (https://github.com/moooofly/harborctl/issues/18)
        - [x] vulnerability
    - [x] signature (https://github.com/moooofly/harborctl/issues/15)
    - [x] scanall (https://github.com/moooofly/harborctl/issues/16)
- [x] log (https://github.com/moooofly/harborctl/issues/6)
- [x] scan
    - [x] log (https://github.com/moooofly/harborctl/issues/29)
- [x] replication
    - [x] list (https://github.com/moooofly/harborctl/issues/28)
    - [x] update
    - [x] delete
    - [x] policy
        - [x] list
        - [x] get
        - [x] create (https://github.com/moooofly/harborctl/issues/30, https://github.com/moooofly/harborctl/issues/31)
        - [x] update (https://github.com/moooofly/harborctl/issues/33)
        - [x] delete (https://github.com/moooofly/harborctl/issues/32)
    - [x] trigger
    - [x] log
- [x] label
    - [x] list
    - [x] create (https://github.com/moooofly/harborctl/issues/22)
    - [x] get
    - [x] update (https://github.com/moooofly/harborctl/issues/25)
    - [x] delete
    - [x] resource
- [x] target
    - [x] list
    - [x] get
    - [x] delete
    - [x] create
    - [x] update
    - [x] policy
    - [x] ping (https://github.com/moooofly/harborctl/issues/34)
- [x] internal
    - [x] syncregistry (https://github.com/moooofly/harborctl/issues/27)
- [x] systeminfo
    - [x] get
    - [x] volume
    - [x] getcert
- [x] usergroup
    - [x] list
    - [x] create
    - [x] get
    - [x] update
    - [x] delete
- [x] chartrepo
    - [x] health
    - [x] chart
        - [x] list
        - [x] upload - 500 error
        - [x] get
        - [x] delete (https://github.com/moooofly/harborctl/issues/43)
        - [x] version
            - [x] get
            - [x] delete
        - [x] label
            - [x] get (https://github.com/moooofly/harborctl/issues/44)
            - [x] delete (https://github.com/moooofly/harborctl/issues/45)
            - [x] attach (https://github.com/moooofly/harborctl/issues/46)
    - [x] prov
        - [x] upload - 500 error
    - [x] library
        - [x] upload (https://github.com/moooofly/harborctl/issues/47)

**Comment by steven-zou** [comment]
Some comments:

  * Move `system gc` out of the base release(V1.6) as it's released in V1.7 and create an issue to track that work
 * Move `configuration` and `email` related out of the base release as it's the priority is low, and create an issue to track that work
 * Move `ldap` related out of the base release as it can be counted in the `configuration` part, and create an issue to track that work
 * Suggest move the complicated commands like`statistic` and tag `retention` policy out of the base release, those features can be supported as plugins of CLI in future. Issues should be created for tracking
* Suggest change `target` to `registry`
* Suggest use `replication` instead of `job`: `harborctl replication policy *` / `harborctl replication run *` / `harborctl replication log *` etc.
* Suggest use `vulnerability` instead of `job` for the scanning-related commands

**Comment by moooofly** [comment]
> Suggest use vulnerability instead of job for the scanning-related commands

After discussion with @steven-zou , the suggest above will not be considered right now.

**Comment by moooofly** [comment]
> update on 2019-01-23

Find `/usergroups` APIs are related to LDAP too, but I have fulfilled these APIs already.

**Comment by moooofly** [comment]
All APIs are support now, hooray @steven-zou
